export const throwError = async (err:any)=>{
    console.warn(err)
}